using System.Reflection;
using FVN_REGISTER.Core.Attributes;
using Microsoft.AspNetCore.Components;

namespace FVN_REGISTER.Web.Security;

/// <summary>
/// Manifest generated by the Web host to describe UI capabilities that may require
/// registration in the central security-function registry.
/// Discovery never grants or revokes permissions.
/// </summary>
public sealed record SecurityDiscoveryManifestEntry(
    string FunctionKey,
    string Module,
    string Action,
    string Source,
    string SourceType,
    string? Route,
    string? Component,
    string DisplayName,
    string Description);

public static class SecurityDiscoveryManifestBuilder
{
    private static readonly string[] ActionTokens =
    [
        "Create", "Add", "Edit", "Update", "Delete", "Remove", "Manage",
        "Approve", "Reject", "Cancel", "Submit", "Save", "Confirm", "Validate",
        "Assign", "Unassign", "Change", "Configure", "Execute", "Reconcile",
        "Preview", "Search", "Filter", "Refresh", "Calculate", "Recalculate",
        "Import", "Export", "Excel", "Print", "Download", "Upload",
        "Handover", "Transfer", "Return", "Repair", "Sync", "Publish",
        "Archive", "Restore", "Lock", "Unlock", "Reset", "Notify", "Send",
        "TwoFactor", "2FA", "Settings", "Detail", "List", "View"
    ];

    private static readonly HashSet<string> IgnoredMethodNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "BuildRenderTree", "OnInitialized", "OnInitializedAsync", "OnParametersSet", "OnParametersSetAsync",
        "OnAfterRender", "OnAfterRenderAsync", "Dispose", "DisposeAsync", "SetParametersAsync",
        "ShouldRender", "ToString", "Equals", "GetHashCode", "MemberwiseClone"
    };

    public static IReadOnlyList<SecurityDiscoveryManifestEntry> Discover(IEnumerable<Assembly> assemblies)
    {
        var result = new List<SecurityDiscoveryManifestEntry>();

        foreach (var assembly in assemblies.Distinct())
        {
            Type[] types;
            try { types = assembly.GetTypes(); }
            catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t is not null).Cast<Type>().ToArray(); }

            foreach (var type in types)
            {
                var route = type.GetCustomAttribute<RouteAttribute>()?.Template;
                AddExplicitDefinition(type, null, route, assembly, result);

                foreach (var method in type.GetMethods(
                    BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly))
                {
                    if (method.IsSpecialName || method.IsConstructor || IgnoredMethodNames.Contains(method.Name))
                        continue;

                    AddExplicitDefinition(type, method, route, assembly, result);

                    var token = ActionTokens.FirstOrDefault(x => method.Name.Contains(x, StringComparison.OrdinalIgnoreCase));
                    if (token is null) continue;

                    var module = GetModule(type);
                    var action = NormalizeAction(token);
                    var functionKey = $"{module}.{action}";
                    result.Add(new SecurityDiscoveryManifestEntry(
                        functionKey,
                        module,
                        action,
                        assembly.GetName().Name ?? "Web",
                        "UI",
                        route,
                        type.FullName,
                        ToDisplayName(action),
                        ToDescription(action, module)));
                }
            }
        }

        return result
            .Where(x => !string.IsNullOrWhiteSpace(x.FunctionKey))
            .GroupBy(x => new { x.FunctionKey, x.Source, x.Component })
            .Select(g => g.First())
            .OrderBy(x => x.FunctionKey, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    private static void AddExplicitDefinition(
        Type type,
        MemberInfo? member,
        string? route,
        Assembly assembly,
        ICollection<SecurityDiscoveryManifestEntry> result)
    {
        var attribute = member?.GetCustomAttribute<SecurityFunctionDefinitionAttribute>()
            ?? type.GetCustomAttribute<SecurityFunctionDefinitionAttribute>();
        if (attribute is null || string.IsNullOrWhiteSpace(attribute.FunctionKey)) return;

        var module = attribute.ModuleCode ?? GetModule(type);
        var action = attribute.ActionCode ?? GetAction(attribute.FunctionKey);
        result.Add(new SecurityDiscoveryManifestEntry(
            attribute.FunctionKey,
            module,
            action ?? "View",
            assembly.GetName().Name ?? "Web",
            "ExplicitMetadata",
            route,
            type.FullName,
            attribute.DisplayName ?? SecurityFunctionCatalog.GetDisplayName(attribute.FunctionKey),
            SecurityFunctionCatalog.GetDescription(attribute.FunctionKey)));
    }

    private static string GetModule(Type type)
    {
        var name = type.Namespace?.Split('.').LastOrDefault();
        return string.IsNullOrWhiteSpace(name) ? "Web" : name;
    }

    private static string GetAction(string functionKey)
        => functionKey.Contains('.') ? functionKey[(functionKey.IndexOf('.') + 1)..] : "View";

    private static string NormalizeAction(string token) => token switch
    {
        "TwoFactor" or "2FA" => "ManageTwoFactor",
        "Recalculate" => "Calculate",
        "Export" or "Excel" => "Export",
        _ => token
    };

    private static string ToDisplayName(string action) => action switch
    {
        "Create" or "Add" => "Thêm",
        "Edit" or "Update" => "Cập nhật",
        "Delete" or "Remove" => "Xóa",
        "Manage" => "Quản lý",
        "Approve" => "Phê duyệt",
        "Reject" => "Từ chối",
        "Cancel" => "Hủy",
        "Submit" => "Gửi xử lý",
        "Save" => "Lưu",
        "Confirm" => "Xác nhận",
        "Validate" => "Kiểm tra",
        "Assign" => "Phân công",
        "Unassign" => "Hủy phân công",
        "Change" => "Thay đổi",
        "Configure" or "Settings" => "Cấu hình",
        "Execute" => "Thực hiện",
        "Reconcile" => "Đối soát",
        "Preview" => "Xem trước",
        "Search" => "Tìm kiếm",
        "Filter" => "Lọc",
        "Refresh" => "Làm mới",
        "Calculate" => "Tính toán",
        "Import" => "Nhập dữ liệu",
        "Export" => "Xuất dữ liệu",
        "Print" => "In",
        "Download" => "Tải xuống",
        "Upload" => "Tải lên",
        "Handover" => "Bàn giao",
        "Transfer" => "Điều chuyển",
        "Return" => "Thu hồi",
        "Repair" => "Sửa chữa",
        "Sync" => "Đồng bộ",
        "Publish" => "Công bố",
        "Archive" => "Lưu trữ",
        "Restore" => "Khôi phục",
        "Lock" => "Khóa",
        "Unlock" => "Mở khóa",
        "Reset" => "Đặt lại",
        "Notify" => "Thông báo",
        "Send" => "Gửi",
        "ManageTwoFactor" => "Quản lý xác thực hai lớp",
        "Detail" => "Xem chi tiết",
        "List" => "Xem danh sách",
        "View" => "Xem",
        _ => action
    };

    private static string ToDescription(string action, string module)
        => $"Thao tác {ToDisplayName(action).ToLowerInvariant()} của phân hệ {module}.";
}
